				(Display	
				  "Meanwhile,\n
					Back at the F.B.I.'s\n
					Mission Control Headquarters"
					#p_mode:		teJustCenter
					#p_color: 	colVLRed
					#p_font:		niceFont
					#p_width:	318
					#p_at: 		1 (- 89 (/ (* 14 3) 2))
					;           ³             ³  ³  ³  
					;           ³             ³  ³  ÀÄ this must be 2 
					;           ³             ³  ÀÄÄÄÄ make this # of lines in msg
					;           ³             ÀÄÄÄÄÄÄÄ make this font height
					;           ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ this must be 1
				)
