castoff
del C:\LL5\%vcsid%\pcopy.log
L:
cd \games\LL5\prog
C:\LL5\%vcsid%\pcopy script\*.*		C:\LL5\script		/lg/u/ex/eq/dy%1
C:\LL5\%vcsid%\pcopy pic\*.*			C:\LL5\pic			/lg/u/ex/eq%1
C:\LL5\%vcsid%\pcopy view\*.*			C:\LL5\view			/lg/u/ex/eq%1
C:\LL5\%vcsid%\pcopy system\*.*		C:\LL5\system		/lg/u/ex/eq/dy/e/ro%1
C:\LL5\%vcsid%\pcopy cursor\*.*		C:\LL5\cursor		/lg/u/ex/eq%1
C:\LL5\%vcsid%\pcopy font\*.*			C:\LL5\font			/lg/u/ex/eq%1
C:\LL5\%vcsid%\pcopy sound\*.*		C:\LL5\sound		/lg/u/ex/eq%1
C:\LL5\%vcsid%\pcopy %vcsid%\*.*		C:\LL5\%vcsid%		/lg/u/ex/eq%1
C:
cd \LL5\%vcsid%
caston
