;**
;**	sound.sh -- 
;**
;**	LSL5:  Passionate Patti Does A Little Undercover Work
;**				Copyright 1991
;**				by Al Lowe
;**
;**	Last Update:	June 20, 1991
;**
;**		Note:  Lines that begin with a semicolon (";") indicate sounds
;**	that are used in only one scene.
;**



;ษอออออออออออออออออออป
;บ                   บ
;บ Miscellaneous     บ
;บ                   บ
;ศอออออออออออออออออออผ

(define		sPointsSnd			010)

;(define		sPhoneKey1			021)
;(define		sPhoneKey2			022)
;(define		sPhoneKey3			023)
;(define		sPhoneKey4			024)
;(define		sPhoneKey5			025)
;(define		sPhoneKey6			026)
;(define		sPhoneKey7			027)
;(define		sPhoneKey8			028)
;(define		sPhoneKey9			029)
;(define		sPhoneKey0			030)
;(define		sPhoneKey#			031)
;(define		sPhoneKey*			032)
;(define		sDialTone			033)
;(define		sCoinInPhone		034)
;(define		sWrongNumber		035)
;(define		sPickup				036)
;(define		sHangup				037)

(define		sDoorOpen			040)
(define		sDoorClose			041)




;ษอออออออออออออออออออป
;บ                   บ
;บ Opening Sequence  บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mMainTheme						100)
;(define		sFootInBucket		101)
;(define		sTypewriter			102)
;(define		sBroomUp				103)
;(define		sGlueStretch		104)
;(define		sBackSpace			105)
;(define		sAooga				106)

;(define	mRepriseTheme					110)


;ษอออออออออออออออออออป
;บ                   บ
;บ Larry Cartoon     บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mMobOffice						120)

;(define	mMobOfficeHit					130)

;(define	mPortProdOffice				140)
;(define		sBreakPot			146)
;(define		sYeow!				147)
;(define		sIdea					148)

;(define	mPlan								150)


;ษอออออออออออออออออออป
;บ                   บ
;บ Porn Prod Corp    บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mPPCMusak						160)
;(define		sCoffee!				161)
;(define		sPlugIn				162)
;(define		sWaterCooler		163)

;(define		sDrawer				171)
;(define		sDegausser			172)

;(define		sFileOpen			181)
;(define		sFileClose			182)

(define		sCarDoorOpen		191)
(define		sCarDoorClose		192)
;(define		sFountain			193)
(define		sCarDriveAway		194)


;ษอออออออออออออออออออป
;บ                   บ
;บ Limousine         บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define		sTVClickOn			201)
;(define		sWindowUpDown		202)
;(define		sFaxFX				203)
;(define		sCarSnd				204)
;(define		sFish					205)
;(define		sTVStatic			206)


;ษอออออออออออออออออออป
;บ                   บ
;บ Meanwhile Scenes  บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mMrBiggTheme					210)

;(define	mMcGutterSlugTheme			215)

;(define	mJimBaker						220)


;ษอออออออออออออออออออป
;บ                   บ
;บ Patti Dreams      บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mDreamTheme						230)
;(define		sCoinsFall			241)


;ษอออออออออออออออออออป
;บ                   บ
;บ Airport           บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define		sAirportExtFX		251)
;(define		sFlyBy				254)
(define		sCarPullsUp			255)
;(define		sATMFX				256)
;(define		sTicket				257)
;(define		sCardSlot			258)
;(define		sPrintTicket		259)	;dump?

;(define		sFootfall1			260)
;(define		sFootfall2			261)
;(define		sSlotPullSpin		262)
;(define		sWinAQuarter		263)

;(define		sCameraMove			271)
;(define		sCameraNod			272)
;(define		sAnnouncement1		273)
;(define		sAnnouncement2		274)
;(define		sAnnouncement3		275)

;(define		sTrickChair			291)
;(define		sSuckPass			292)
;(define		sSlidingDoor		293)
;(define		sCrowd				294)
;(define		sTrickChairHit		295)
;(define		sCuckoo				296)
;(define		sAnnouncement		297)


;ษอออออออออออออออออออป
;บ                   บ
;บ Airplane          บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define		sTakeOff				311)
;(define		sLand					312)
;(define		sBounceLanding		313)
;(define		sBrakes				314)
;(define		sTraveling			315)
;(define	mTraveling						315)


;ษอออออออออออออออออออป
;บ                   บ
;บ Larry Dreams      บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mDreamLand						320)
;(define		sPlaneSnd			321)
;(define		sSqueezeNuts		322)

;(define	mMozart							330)
;(define		sApplause			331)

;(define	mSexySax							345)
;(define	mMusicEnds						346)
;(define		sZipper						347)

;(define	mGondola							350)
;(define		sPoleToing			351)
;(define		sSpringLeak			352)

;(define	mJazzPop							370)

;(define	mOboeSnake						375)

;(define	mAsTimeGoesBy					380)
;(define		sDC3Engines			381)


;ษอออออออออออออออออออป
;บ                   บ
;บ Flight Stimulator บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define		sPlaneDive			386)
;(define		sScreams				387)

;(define	mFalling							390)
;(define	mSavePlane						391)
;(define		sPullOut				392)
;(define		sGaugeFX1			393)
;(define		sGaugeFX2			394)
;(define		sGaugeFX3			395)
;(define		sPullIn				396)


;ษอออออออออออออออออออป
;บ                   บ
;บ Patti Cartoon     บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define		sOneHandClap		401)
;(define		sPFootfall			402)
;(define		sPFootCreak			403)
;(define		sPFootfall2			404)			;TBA

;(define	mStiffed							405)

;(define	mDesmondTheme					410)

;(define	mDesmond2						420)
;(define	mDesmond3						425)


;ษอออออออออออออออออออป
;บ                   บ
;บ FBI Lab           บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define		sVibratorOn			431)
;(define		sVibratorShoots	432)
;(define		sVibratorHits		433)
;(define		sShootingBra		434)
;(define		sRachetBra			435)
(define		sLabSounds1			436)	;used in 430, 440, 435, 445

;(define		sKeyboardType		442)
;(define		sLongFart			443)
;(define		sBodyBulge1			444)
;(define		sBodyBulge2			445)
;(define		sBodyBulge3			446)
;(define		sBoing1				447)
;(define		sBoing2				448)
;(define		sBoing3				449)

;(define	mVonPelt1						450)
;(define	mVonPelt2						451)
;(define	mVonPelt3						452)
;(define	mVonPelt4						453)
;(define	mVonPelt5						454)
;(define		sDrill						455)

;(define	mVonPeltDone					458)


;ษอออออออออออออออออออป
;บ                   บ
;บ Closing Sequence  บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mDinnerMusic					460)
;(define	mPattiHero						461)
;(define	mEnding							462)
;(define	mLarryBigg						463)
;(define		sPieInFace			464)

;(define	mPattiBigg						465)
;(define	mPullGun							466)	; should be sPullGun??
;(define		sDinnerFX					467)
;(define		sHelicopter					468)	; TBA

;(define	mLoveTheme						470)

;(define		sBetterBabes				481)
;(define		sSQ4Belch					482)
;(define		sSQ4Barf						483)
;(define		sLarryFart					484)


;ษอออออออออออออออออออป
;บ                   บ
;บ Hard Disk Cafe    บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mHardRock1						500)
;(define	mHardRock2						500)
;(define	mHardRock3						500)

;(define	mMusicBox						510)
;(define		sMachineFX			511)
;(define		sGetTape				512)

;(define		sFatSlob				526)
;(define	mMichelle						535)
;(define		sGetsCherry			536)
;(define		sBanana				537)
;(define	mMichelle2						538)

;(define		sShocked				561)


;ษอออออออออออออออออออป
;บ                   บ
;บ Shill Building    บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mStruggling						600)
;(define		sStruggle			601)

;(define		sRevolvingDoor		611)

;(define	mShillMusak						620)
;(define		sElevatorDing		621)
;(define		sElevatorDoor		622)

;(define	mSong33Forward					640)
;(define	mSong78Forward					641)
;(define	mSong33Backward				642)
;(define	mSong78Backward				643)
;(define		sMessage1			644)
;(define		sMessage2			645)
;(define		sMessage3			646)
;(define		sNeedleDownSpin	648)

;(define	mPopTune							660)
;(define		sRewind				661)
;(define		sStop					662)
;(define	mGettingSome					663)
;(define		sGlassesClink		664)
;(define		sZing					665)

;(define		sSonarPing			691)


;ษอออออออออออออออออออป
;บ                   บ
;บ Tramps Casino     บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mBoardWalk						700)

;(define	mCasino							710)
;(define		sCasinoFX			711)

;(define		sDeal					721)
;(define		sButton				722)
;(define		sCashOut				723)
;(define		sWin					724)
;(define		sBigWin				725)
;(define		sLose					726)

;(define	mNastyBoys						738)

;(define	mMudWrestling					740)
;(define		sCrowdRumble		741)
;(define		sCrowdRoar			742)
;(define		sCatCalls			743)
;(define		sMudSquishing		744)

;(define	mCan'tGetItUp					750)
;(define		sCrowdGasp			751)
;(define		sGirlAh				752)
;(define		sGirlOh				753)
;(define		sGirlOo				754)
;(define		sGirlAh?				755)
;(define		sGirlOh?				756)
;(define		sGirlOo?				757)
;(define		sGirlLarryUm		758)

;(define		sSplash				761)

;(define	mSkateShop						790)	;TBA


;ษอออออออออออออออออออป
;บ                   บ
;บ K-RAP Radio       บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mKRAPRap1						800)
;(define	mKRAPRap2						801)
;(define	mKRAPRap3						802)

;(define		sCopyMachine		841)
;(define		sCopyExplodes		842)
;(define		sPickLock			843)

;(define		sFlush				851)
;(define		sRunWater			852)
;(define		sElevator			853)
;(define		sElevatorClose		854)

;(define		sWolfWhistle		861)
;(define		sZwoosh!				862)

;(define		sUseMike				891)
;(define		sBreakGlass			892)			;TBA
;(define		sReelMt				893)			;TBA


;ษอออออออออออออออออออป
;บ                   บ
;บ Doc Pulliams      บ
;บ                   บ
;ศอออออออออออออออออออผ

;(define	mDentistMusak					905)

;(define	mSalsa							910)
;(define		sKnockGlass			911)			;TBA
;(define		sSuction				912)			;TBA
;(define		sHitWall				913)			;TBA
;(define		sHitBalls			914)			;TBA
;(define		sSlideDown			915)			;TBA

;(define	mSalsaComic						920)
